// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysVentas.Facturation.Infrastructure.Data;

#nullable disable

namespace SysVentas.Facturation.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FacturationDataContext))]
    [Migration("20220526043800_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SysVentas.Facturacion.Domain.InvoiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("InvoiceMasterId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(17,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(17,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceMasterId");

                    b.ToTable("InvoiceDetail", "Facturation");
                });

            modelBuilder.Entity("SysVentas.Facturacion.Domain.InvoiceMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(17,2)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceMaster", "Facturation");
                });

            modelBuilder.Entity("SysVentas.Facturacion.Domain.InvoiceDetail", b =>
                {
                    b.HasOne("SysVentas.Facturacion.Domain.InvoiceMaster", "InvoiceMaster")
                        .WithMany("Details")
                        .HasForeignKey("InvoiceMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceMaster");
                });

            modelBuilder.Entity("SysVentas.Facturacion.Domain.InvoiceMaster", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
